name: Update year

on:
  schedule:
    - cron: '30 23 31 12 *'


jobs:
  build:
    name: Automatic year update
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git
    - name: Upstream branches
      run: |
        git config --global user.name "${GITHUB_USER}"
        git config --global user.email "${GITHUB_EMAIL}"
        git clone https://"${GITHUB_USER}":"${GITHUB_TOKEN}"@github.com/"${GITHUB_USER}"/releases.git
        cd releases
        export thisyear=$(date +%Y)
        export nextyear=$((thisyear + 1))
        sed -i "s|${thisyear}|${nextyear}|g" build.sh
        git add build.sh
        git commit -s -m "build: it's ${nextyear} time"
        git push
      env:
        GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_KEY }}
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
